/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ItineraryService } from "../itinerary.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ItineraryCreateInput } from "./ItineraryCreateInput";
import { Itinerary } from "./Itinerary";
import { ItineraryFindManyArgs } from "./ItineraryFindManyArgs";
import { ItineraryWhereUniqueInput } from "./ItineraryWhereUniqueInput";
import { ItineraryUpdateInput } from "./ItineraryUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ItineraryControllerBase {
  constructor(
    protected readonly service: ItineraryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Itinerary })
  @nestAccessControl.UseRoles({
    resource: "Itinerary",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createItinerary(
    @common.Body() data: ItineraryCreateInput
  ): Promise<Itinerary> {
    return await this.service.createItinerary({
      data: {
        ...data,

        accommodation: data.accommodation
          ? {
              connect: data.accommodation,
            }
          : undefined,

        destination: data.destination
          ? {
              connect: data.destination,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        accommodation: {
          select: {
            id: true,
          },
        },

        activities: true,
        createdAt: true,

        destination: {
          select: {
            id: true,
          },
        },

        endDate: true,
        id: true,
        startDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Itinerary] })
  @ApiNestedQuery(ItineraryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Itinerary",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async itineraries(@common.Req() request: Request): Promise<Itinerary[]> {
    const args = plainToClass(ItineraryFindManyArgs, request.query);
    return this.service.itineraries({
      ...args,
      select: {
        accommodation: {
          select: {
            id: true,
          },
        },

        activities: true,
        createdAt: true,

        destination: {
          select: {
            id: true,
          },
        },

        endDate: true,
        id: true,
        startDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Itinerary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Itinerary",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async itinerary(
    @common.Param() params: ItineraryWhereUniqueInput
  ): Promise<Itinerary | null> {
    const result = await this.service.itinerary({
      where: params,
      select: {
        accommodation: {
          select: {
            id: true,
          },
        },

        activities: true,
        createdAt: true,

        destination: {
          select: {
            id: true,
          },
        },

        endDate: true,
        id: true,
        startDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Itinerary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Itinerary",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateItinerary(
    @common.Param() params: ItineraryWhereUniqueInput,
    @common.Body() data: ItineraryUpdateInput
  ): Promise<Itinerary | null> {
    try {
      return await this.service.updateItinerary({
        where: params,
        data: {
          ...data,

          accommodation: data.accommodation
            ? {
                connect: data.accommodation,
              }
            : undefined,

          destination: data.destination
            ? {
                connect: data.destination,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          accommodation: {
            select: {
              id: true,
            },
          },

          activities: true,
          createdAt: true,

          destination: {
            select: {
              id: true,
            },
          },

          endDate: true,
          id: true,
          startDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Itinerary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Itinerary",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteItinerary(
    @common.Param() params: ItineraryWhereUniqueInput
  ): Promise<Itinerary | null> {
    try {
      return await this.service.deleteItinerary({
        where: params,
        select: {
          accommodation: {
            select: {
              id: true,
            },
          },

          activities: true,
          createdAt: true,

          destination: {
            select: {
              id: true,
            },
          },

          endDate: true,
          id: true,
          startDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: ItineraryWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        bookingDate: true,
        bookingStatus: true,
        createdAt: true,
        id: true,

        itinerary: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "Itinerary",
    action: "update",
    possession: "any",
  })
  async connectBookings(
    @common.Param() params: ItineraryWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateItinerary({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "Itinerary",
    action: "update",
    possession: "any",
  })
  async updateBookings(
    @common.Param() params: ItineraryWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateItinerary({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  @nestAccessControl.UseRoles({
    resource: "Itinerary",
    action: "update",
    possession: "any",
  })
  async disconnectBookings(
    @common.Param() params: ItineraryWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateItinerary({
      where: params,
      data,
      select: { id: true },
    });
  }
}
