/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Destination } from "./Destination";
import { DestinationCountArgs } from "./DestinationCountArgs";
import { DestinationFindManyArgs } from "./DestinationFindManyArgs";
import { DestinationFindUniqueArgs } from "./DestinationFindUniqueArgs";
import { CreateDestinationArgs } from "./CreateDestinationArgs";
import { UpdateDestinationArgs } from "./UpdateDestinationArgs";
import { DeleteDestinationArgs } from "./DeleteDestinationArgs";
import { ItineraryFindManyArgs } from "../../itinerary/base/ItineraryFindManyArgs";
import { Itinerary } from "../../itinerary/base/Itinerary";
import { DestinationService } from "../destination.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Destination)
export class DestinationResolverBase {
  constructor(
    protected readonly service: DestinationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Destination",
    action: "read",
    possession: "any",
  })
  async _destinationsMeta(
    @graphql.Args() args: DestinationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Destination])
  @nestAccessControl.UseRoles({
    resource: "Destination",
    action: "read",
    possession: "any",
  })
  async destinations(
    @graphql.Args() args: DestinationFindManyArgs
  ): Promise<Destination[]> {
    return this.service.destinations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Destination, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Destination",
    action: "read",
    possession: "own",
  })
  async destination(
    @graphql.Args() args: DestinationFindUniqueArgs
  ): Promise<Destination | null> {
    const result = await this.service.destination(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Destination)
  @nestAccessControl.UseRoles({
    resource: "Destination",
    action: "create",
    possession: "any",
  })
  async createDestination(
    @graphql.Args() args: CreateDestinationArgs
  ): Promise<Destination> {
    return await this.service.createDestination({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Destination)
  @nestAccessControl.UseRoles({
    resource: "Destination",
    action: "update",
    possession: "any",
  })
  async updateDestination(
    @graphql.Args() args: UpdateDestinationArgs
  ): Promise<Destination | null> {
    try {
      return await this.service.updateDestination({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Destination)
  @nestAccessControl.UseRoles({
    resource: "Destination",
    action: "delete",
    possession: "any",
  })
  async deleteDestination(
    @graphql.Args() args: DeleteDestinationArgs
  ): Promise<Destination | null> {
    try {
      return await this.service.deleteDestination(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Itinerary], { name: "itineraries" })
  @nestAccessControl.UseRoles({
    resource: "Itinerary",
    action: "read",
    possession: "any",
  })
  async findItineraries(
    @graphql.Parent() parent: Destination,
    @graphql.Args() args: ItineraryFindManyArgs
  ): Promise<Itinerary[]> {
    const results = await this.service.findItineraries(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
