/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  ValidateNested,
  IsEnum,
} from "class-validator";

import { ItineraryCreateNestedManyWithoutDestinationsInput } from "./ItineraryCreateNestedManyWithoutDestinationsInput";
import { Type } from "class-transformer";
import { EnumDestinationScenicViews } from "./EnumDestinationScenicViews";

@InputType()
class DestinationCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  airQuality?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  city?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  costOfLiving?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
    type: () => ItineraryCreateNestedManyWithoutDestinationsInput,
  })
  @ValidateNested()
  @Type(() => ItineraryCreateNestedManyWithoutDestinationsInput)
  @IsOptional()
  @Field(() => ItineraryCreateNestedManyWithoutDestinationsInput, {
    nullable: true,
  })
  itineraries?: ItineraryCreateNestedManyWithoutDestinationsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  safetyRating?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumDestinationScenicViews,
    isArray: true,
  })
  @IsEnum(EnumDestinationScenicViews, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumDestinationScenicViews], {
    nullable: true,
  })
  scenicViews?: Array<"Option1">;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  wifiReliability?: number | null;
}

export { DestinationCreateInput as DestinationCreateInput };
